### ISSUE TITLE
failing to build on node 11.0.0

### ISSUE THREAD

**Issue by drewfish** [bnoordhuis/node-heapdump#121]
I'm seeing the following errors:
```cpp
  CXX(target) Release/obj.target/addon/src/heapdump.o
In file included from ../src/heapdump.cc:17:0:
../src/compat-inl.h: In static member function ‘static void compat::CpuProfiler::StartCpuProfiling(v8::Isolate*, v8::Local<v8::String>)’:
../src/compat-inl.h:300:19: error: ‘class v8::Isolate’ has no member named ‘GetCpuProfiler’; did you mean ‘GetHeapProfiler’?
   return isolate->GetCpuProfiler()->StartProfiling(title, record_samples);
                   ^~~~~~~~~~~~~~
../src/compat-inl.h:300:73: error: return-statement with a value, in function returning 'void' [-fpermissive]
   return isolate->GetCpuProfiler()->StartProfiling(title, record_samples);
                                                                         ^
../src/compat-inl.h: In static member function ‘static const v8::CpuProfile* compat::CpuProfiler::StopCpuProfiling(v8::Isolate*, v8::Local<v8::String>)’:
../src/compat-inl.h:310:19: error: ‘class v8::Isolate’ has no member named ‘GetCpuProfiler’; did you mean ‘GetHeapProfiler’?
   return isolate->GetCpuProfiler()->StopProfiling(title);
                   ^~~~~~~~~~~~~~
```

**Comment by bnoordhuis** [comment]
Fixed in v0.3.10.
