### ISSUE TITLE
Doesn't compile on CentOS 6.2

### ISSUE THREAD

**Issue by brandonramirez** [bnoordhuis/node-heapdump#1]
$ npm install heapdump
npm http GET https://registry.npmjs.org/heapdump
npm http 304 https://registry.npmjs.org/heapdump

> heapdump@0.0.1 install /home/brandon/dev/node_modules/heapdump
> node-gyp rebuild

info it worked if it ends with ok
spawn python [ '/home/brandon/.node-gyp/0.6.19/tools/gyp_addon',
  'binding.gyp',
  '-I/home/brandon/dev/node_modules/heapdump/build/config.gypi',
  '-f',
  'make' ]
spawn make [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/home/brandon/dev/node_modules/heapdump/build'
  CXX(target) Release/obj.target/heapdump/src/heapdump.o
../src/heapdump.cc: In function âvoid<unnamed>::Init(v8::Handle<v8::Object>)â:
../src/heapdump.cc:130: error: memset was not declared in this scope
make: *** [Release/obj.target/heapdump/src/heapdump.o] Error 1
make: Leaving directory`/home/brandon/dev/node_modules/heapdump/build'
ERR! Error: `make` failed with exit code: 2
    at ChildProcess.onExit (/home/brandon/nvm/v0.6.19/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:212:23)
    at ChildProcess.emit (events.js:70:17)
    at maybeExit (child_process.js:362:16)
    at Process.onexit (child_process.js:398:5)
ERR! not ok

npm ERR! heapdump@0.0.1 install: `node-gyp rebuild`
npm ERR! `sh "-c" "node-gyp rebuild"` failed with 1
npm ERR!
npm ERR! Failed at the heapdump@0.0.1 install script.
npm ERR! This is most likely a problem with the heapdump package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls heapdump
npm ERR! There is likely additional logging output above.
npm ERR!
npm ERR! System Linux 2.6.32-220.23.1.el6.x86_64
npm ERR! command "node" "/home/brandon/nvm/v0.6.19/bin/npm" "install" "heapdump"
npm ERR! cwd /home/brandon/dev
npm ERR! node -v v0.6.19
npm ERR! npm -v 1.1.24
npm ERR! code ELIFECYCLE
npm ERR! message heapdump@0.0.1 install: `node-gyp rebuild`
npm ERR! message `sh "-c" "node-gyp rebuild"` failed with 1
npm ERR! errno {}
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/brandon/dev/npm-debug.log
npm not ok
npm not ok
$ cat /etc/centos-release
CentOS release 6.2 (Final)
$
