### ISSUE TITLE
The module fails to build with NodeJS version 7.8.0 on Linux 4.8.12-040812-generic

### ISSUE THREAD

**Issue by mykola-mokhnach** [bnoordhuis/node-heapdump#99]
Got the following compilation error while trying to install heapdump with npm on Linux:

```
> heapdump@0.3.9 install /home/travis/build/appium/appium/node_modules/heapdump
> node-gyp rebuild
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory `/home/travis/build/appium/appium/node_modules/heapdump/build'
  CXX(target) Release/obj.target/addon/src/heapdump.o
In file included from /home/travis/.node-gyp/7.8.0/include/node/node.h:42:0,
                 from ../src/heapdump.cc:15:
/home/travis/.node-gyp/7.8.0/include/node/v8.h:348:1: error: expected unqualified-id before ‘using’
/home/travis/.node-gyp/7.8.0/include/node/v8.h:477:51: error: ‘virtual v8::EmbedderReachableReferenceReporter::~EmbedderReachableReferenceReporter()’ declared virtual cannot be defaulted in the class body
/home/travis/.node-gyp/7.8.0/include/node/v8.h:870:1: error: expected unqualified-id before ‘using’
/home/travis/.node-gyp/7.8.0/include/node/v8.h:6178:35: error: ‘virtual v8::EmbedderHeapTracer::~EmbedderHeapTracer()’ declared virtual cannot be defaulted in the class body
In file included from ../src/compat.h:20:0,
                 from ../src/compat-inl.h:18,
                 from ../src/heapdump.cc:17:
/home/travis/.node-gyp/7.8.0/include/node/v8-profiler.h:57:35: error: ‘virtual v8::TracingCpuProfiler::~TracingCpuProfiler()’ declared virtual cannot be defaulted in the class body
../src/heapdump.cc:52:11: error: ‘v8::Handle’ has not been declared
make: *** [Release/obj.target/addon/src/heapdump.o] Error 1
make: Leaving directory `/home/travis/build/appium/appium/node_modules/heapdump/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/travis/.nvm/versions/node/v7.8.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.8.12-040812-generic
gyp ERR! command "/home/travis/.nvm/versions/node/v7.8.0/bin/node" "/home/travis/.nvm/versions/node/v7.8.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/travis/build/appium/appium/node_modules/heapdump
gyp ERR! node -v v7.8.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
```

Please see https://travis-ci.org/appium/appium/jobs/219286168 for more details

**Comment by bnoordhuis** [comment]
You need a C++11-capable compiler.  Your copy of g++ or clang++ is too old.

**Comment by mykola-mokhnach** [comment]
Thanks. This was also my first guess. Just wanted to make sure it causes the failure.
