### ISSUE TITLE
Does not work with Nodejs v4.1.1

### ISSUE THREAD

**Issue by weekens** [bnoordhuis/node-heapdump#69]
When I try to run a program that imports `heapdump` on Nodejs v4.1.1, I get the following:

```
module.js:338
    throw err;
    ^

Error: Cannot find module '../build/Debug/addon'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/weekens/workspace/saymon/backend/server/node_modules/heapdump/lib/main.js:18:15)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/weekens/workspace/saymon/backend/server/saymon-server.js:31:16)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

The `heapdump` module has the following structure after installing with NPM v4.1.1:
```
node_modules/heapdump/
├── binding.gyp
├── build
│   ├── addon.target.mk
│   ├── binding.Makefile
│   ├── config.gypi
│   ├── Makefile
│   └── Release
│       ├── addon.node
│       └── obj.target
│           ├── addon
│           │   └── src
│           │       └── heapdump.o
│           └── addon.node
├── lib
│   └── main.js
├── LICENSE
├── package.json
├── README.md
├── src
│   ├── compat.h
│   ├── compat-inl.h
│   ├── heapdump.cc
│   ├── heapdump-posix.h
│   └── heapdump-win32.h
└── test
    ├── test-callback.js
    ├── test-callback-without-filename.js
    └── test-sigusr2.js
```

**Comment by bnoordhuis** [comment]
What does `node -p 'require("./node_modules/heapdump/build/Release/addon.node")` print?

**Comment by weekens** [comment]
```
module.js:355
  Module._extensions[extension](this, filename);
                               ^

Error: Module version mismatch. Expected 46, got 14.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at [eval]:1:1
    at Object.exports.runInThisContext (vm.js:54:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:434:26)
    at node.js:566:27
```

**Comment by bnoordhuis** [comment]
There's your problem, the add-on is compiled for the wrong version.  Run `npm rebuild` and make sure `which node` is the v4 binary.

**Comment by weekens** [comment]
@bnoordhuis, you're right. The problem was that node v4 was not in PATH.

I've tried the elementary example with `heapdump` module only, and it wors on v4.

Thanks a lot! Sorry for disturbance!

**Comment by bnoordhuis** [comment]
No problem, glad to hear it's working now.
